import { AppSidebar } from "@/components/app-sidebar";
import { SiteHeader } from "@/components/site-header";
import { ThemeProvider } from "@/components/theme-provider";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    {/* Main layout container with fixed header height */}
                    <div
                        style={{ "--header-height": "4rem" }}
                        className="flex flex-col min-h-screen"
                    >
                        {/* Sidebar provider for responsive layout */}
                        <SidebarProvider
                            defaultOpen={false}
                            className="flex flex-col flex-1"
                        >
                            {/* Fixed site header */}
                            <SiteHeader />

                            {/* Content area with sidebar */}
                            <div className="flex flex-1 bg-background">
                                {/* Main content area */}
                                <SidebarInset>
                                    <main className="flex flex-1 flex-col">
                                        {children}
                                    </main>
                                </SidebarInset>

                                {/* Left sidebar */}
                                <AppSidebar side="left" />
                            </div>
                        </SidebarProvider>
                    </div>
                </ThemeProvider>
            </body>
        </html>
    );
}
